# Generated by Django 5.2.11 on 2026-04-02 11:06

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0005_address_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('message', models.TextField(blank=True)),
                ('inquiry_date', models.DateTimeField(auto_now_add=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='listing', to='listings.listing')),
            ],
        ),
    ]
