# Generated by Django 5.2.11 on 2026-03-13 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(blank=True, max_length=20)),
                ('building_name', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveBigIntegerField()),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.PositiveSmallIntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', models.ImageField(upload_to='house_photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='house_photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='house_photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='house_photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='house_photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='house_photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='house_photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listings.address')),
                ('realtors_listings', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
