# Generated by Django 5.2.11 on 2026-03-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='realtors_listings',
            new_name='relator',
        ),
    ]
