# Generated by Django 5.2.11 on 2026-03-13 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_listing_listing_address_and_more'),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listings_address', to='listings.address'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='relator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='realtors_listings', to='realtors.realtor'),
        ),
    ]
