# Generated by Django 5.2.11 on 2026-03-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_relator_listing_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
